# Generated by Django 5.2.4 on 2025-09-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summerapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
    ]
