# Generated by Django 5.2.4 on 2025-09-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summerapp', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='GST',
            field=models.IntegerField(default='', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default='', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default='', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(default='', null=True),
        ),
    ]
