# Generated by Django 5.2.4 on 2025-09-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summerapp', '0003_product_gst_product_discount_product_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='GST',
        ),
        migrations.AddField(
            model_name='product',
            name='gstin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
