# Generated by Django 5.2.4 on 2025-09-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summerapp', '0009_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='', null=True),
        ),
    ]
