# Generated by Django 5.2.6 on 2025-09-24 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summerapp', '0011_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cartid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='summerapp.cart'),
        ),
        migrations.AlterField(
            model_name='order',
            name='productid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='summerapp.product'),
        ),
    ]
