# Generated by Django 5.2.6 on 2025-09-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summerapp', '0012_order_cartid_alter_order_productid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cartid',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='productid',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
