# Generated by Django 5.2.6 on 2025-09-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summerapp', '0014_order_email_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(default='', max_length=254, null=True),
        ),
    ]
