# Generated by Django 5.2.6 on 2025-09-26 09:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summerapp', '0015_alter_order_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='order',
            new_name='orderItem',
        ),
    ]
