# Generated by Django 5.2.6 on 2025-09-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summerapp', '0016_rename_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='contactno',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
